// Turns an Armory talent payload into classic three-tab talent panels.
//
// Captured trait nodes are placed by the static catalog (node ID → tab, row,
// column) generated by scripts/buildTalentCatalog.mjs. Nodes the catalog does
// not know fall back to their captured coordinates: X positions cluster into
// tabs and snap onto the 4-column grid, Y positions snap onto rows.

const POINTS_PER_ROW = 5
const FIRST_TALENT_LEVEL = 10

function number(value) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

export function selectedEntry(node) {
  return node?.entries?.find((entry) => entry.selected) || node?.entries?.find((entry) => entry.isActiveEntry) || node?.entries?.[0] || null
}

export function nodeRanks(node) {
  const entry = selectedEntry(node)
  const rank = Math.max(0, number(entry?.rank ?? node?.rank) || 0)
  const maxRank = Math.max(rank, number(entry?.maxRank) || number(node?.maxRank) || 1)
  return { rank, maxRank }
}

export function classToken(className) {
  return String(className || '').toUpperCase().replace(/[^A-Z]/g, '')
}

function smallestStep(values) {
  const sorted = [...new Set(values)].sort((a, b) => a - b)
  let step = Infinity
  for (let index = 1; index < sorted.length; index += 1) step = Math.min(step, sorted[index] - sorted[index - 1])
  return Number.isFinite(step) && step > 0 ? step : 1
}

// Groups nodes into tabs by their X coordinate: a gap wider than two grid steps
// starts a new tab.
function clusterByX(nodes) {
  if (!nodes.length) return []
  const step = smallestStep(nodes.map((node) => number(node.x) || 0))
  const sorted = [...nodes].sort((a, b) => (number(a.x) || 0) - (number(b.x) || 0))
  const clusters = [[sorted[0]]]
  for (let index = 1; index < sorted.length; index += 1) {
    const gap = (number(sorted[index].x) || 0) - (number(sorted[index - 1].x) || 0)
    if (gap > step * 2) clusters.push([])
    clusters.at(-1).push(sorted[index])
  }
  return clusters.map((members) => ({ members, step, originX: Math.min(...members.map((node) => number(node.x) || 0)) }))
}

function majorityTab(members, catalog) {
  const counts = new Map()
  for (const node of members) {
    const tabId = catalog?.nodes?.[node.id]?.[0]
    if (tabId) counts.set(tabId, (counts.get(tabId) || 0) + 1)
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? null
}

function fallbackTabName(talents, index, count) {
  const tab = talents?.art?.talentTabs?.[index]
  if (tab?.name) return tab.name
  const definitions = Array.isArray(talents?.treeDefinitions) ? talents.treeDefinitions : []
  if (definitions.length === count && definitions[index]?.name) return definitions[index].name
  if (count === 1) return talents?.name || 'Talents'
  return `Tree ${index + 1}`
}

function pointBudget(talents, spent, level) {
  const reportedSpent = number(talents?.pointsSpent)
  const available = number(talents?.pointsAvailable)
  if (reportedSpent !== null && available !== null) return Math.max(spent, reportedSpent + available)
  const characterLevel = number(level)
  if (characterLevel !== null && characterLevel > 0) return Math.max(spent, characterLevel - FIRST_TALENT_LEVEL + 1)
  return null
}

export function buildTalentLayout(talents, { className, level, catalog } = {}) {
  const nodes = (Array.isArray(talents?.nodes) ? talents.nodes : []).filter((node) => node && node.isVisible !== false)
  const edges = Array.isArray(talents?.edges) ? talents.edges : []
  if (!nodes.length) return null

  const token = classToken(className)
  const classTabs = catalog?.classes?.[token] || []
  const minY = Math.min(...nodes.map((node) => number(node.y) || 0))
  const rowStep = smallestStep(nodes.map((node) => number(node.y) || 0))
  const clusters = clusterByX(nodes)

  // Resolve which tab each X cluster belongs to.
  const panelsByKey = new Map()
  const orderedKeys = classTabs.map((tabId) => `tab-${tabId}`)
  for (const tabId of classTabs) panelsByKey.set(`tab-${tabId}`, { tabId, members: [] })

  clusters.forEach((cluster, index) => {
    let tabId = majorityTab(cluster.members, catalog)
    if (!tabId && classTabs.length === clusters.length) tabId = classTabs[index]
    const key = tabId ? `tab-${tabId}` : `cluster-${index}`
    if (!panelsByKey.has(key)) {
      panelsByKey.set(key, { tabId, members: [], fallbackIndex: index })
      orderedKeys.push(key)
    }
    const panel = panelsByKey.get(key)
    for (const node of cluster.members) {
      const placed = catalog?.nodes?.[node.id]
      const row = placed ? placed[1] : Math.round(((number(node.y) || 0) - minY) / rowStep)
      const col = placed ? placed[2] : Math.max(0, Math.min(3, Math.round(((number(node.x) || 0) - cluster.originX) / cluster.step)))
      panel.members.push({ node, row, col })
    }
  })

  // A node the catalog places in another tab moves there, even if its X
  // coordinate clustered elsewhere.
  for (const panel of panelsByKey.values()) {
    panel.members = panel.members.filter((member) => {
      const tabId = catalog?.nodes?.[member.node.id]?.[0]
      if (!tabId || tabId === panel.tabId || !panelsByKey.has(`tab-${tabId}`)) return true
      panelsByKey.get(`tab-${tabId}`).members.push(member)
      return false
    })
  }

  const visibleKeys = orderedKeys.filter((key) => panelsByKey.get(key).members.length || panelsByKey.get(key).tabId)
  const placements = new Map()
  const catalogRows = number(catalog?.grid?.rows) || 0

  const panels = visibleKeys.map((key, index) => {
    const source = panelsByKey.get(key)
    const tab = source.tabId ? catalog?.tabs?.[source.tabId] : null
    const members = source.members
    const points = members.reduce((sum, member) => sum + nodeRanks(member.node).rank, 0)
    const maxRow = members.reduce((max, member) => Math.max(max, member.row), 0)
    const name = tab?.name || fallbackTabName(talents, source.fallbackIndex ?? index, visibleKeys.length)
    for (const member of members) placements.set(member.node.id, { ...member, panelKey: key })
    return {
      key,
      tabId: source.tabId,
      name,
      points,
      rows: Math.max(maxRow + 1, source.tabId ? catalogRows : 0, 1),
      background: source.tabId ? `/talent-art/${source.tabId}.jpg` : null,
      icon: source.tabId ? `/talent-art/icons/${source.tabId}.jpg` : null,
      members,
    }
  })

  const pointsSpent = panels.reduce((sum, panel) => sum + panel.points, 0)
  const pointsTotal = pointBudget(talents, pointsSpent, level)
  const pointsLeft = pointsTotal === null ? null : Math.max(0, pointsTotal - pointsSpent)
  const nodesById = new Map(nodes.map((node) => [node.id, node]))
  const incoming = new Map()
  for (const edge of edges) {
    if (!nodesById.has(edge?.from) || !nodesById.has(edge?.to)) continue
    if (!incoming.has(edge.to)) incoming.set(edge.to, [])
    incoming.get(edge.to).push(edge.from)
  }

  for (const panel of panels) {
    const tab = panel.tabId ? catalog?.tabs?.[panel.tabId] : null
    panel.nodes = panel.members.map(({ node, row, col }) => {
      const { rank, maxRank } = nodeRanks(node)
      const requirements = []
      const requiredPoints = row * POINTS_PER_ROW
      if (panel.points < requiredPoints && rank === 0) {
        requirements.push(`Requires ${requiredPoints} points in ${panel.name} Talents`)
      }
      for (const sourceId of incoming.get(node.id) || []) {
        const source = nodesById.get(sourceId)
        const sourceRanks = nodeRanks(source)
        if (sourceRanks.rank < sourceRanks.maxRank && rank === 0) {
          const sourceName = selectedEntry(source)?.name || 'the previous talent'
          requirements.push(`Requires ${sourceRanks.maxRank} ${sourceRanks.maxRank === 1 ? 'point' : 'points'} in ${sourceName}`)
        }
      }

      let state = 'locked'
      if (rank > 0) state = rank >= maxRank ? 'maxed' : 'partial'
      else if (!requirements.length && pointsLeft !== 0) state = 'available'

      // Nodes captured with other IDs (synthetic seeds, older builds) borrow
      // rank text from the same-named talent in the resolved tab.
      const catalogId = catalog?.descriptions?.[node.id] ? node.id : tab?.talents?.[selectedEntry(node)?.name]
      const rankText = catalog?.descriptions?.[catalogId] || []
      return {
        node,
        entry: selectedEntry(node),
        row,
        col,
        rank,
        maxRank,
        state,
        requirements,
        currentRankText: rank > 0 ? rankText[rank - 1] || '' : '',
        nextRankText: rank < maxRank ? rankText[rank] || '' : '',
      }
    })
    delete panel.members
  }

  for (const panel of panels) {
    panel.edges = []
    for (const edge of edges) {
      const from = placements.get(edge?.from)
      const to = placements.get(edge?.to)
      if (!from || !to || from.panelKey !== panel.key || to.panelKey !== panel.key) continue
      const sourceRanks = nodeRanks(from.node)
      panel.edges.push({
        key: `${edge.from}-${edge.to}`,
        from: { row: from.row, col: from.col },
        to: { row: to.row, col: to.col },
        active: sourceRanks.rank >= sourceRanks.maxRank,
      })
    }
  }

  return {
    className: token ? String(className) : '',
    panels,
    rows: Math.max(...panels.map((panel) => panel.rows)),
    pointsSpent,
    pointsTotal,
    pointsLeft,
  }
}
